export interface PortfolioItem {
  name: string;
  url: string;
  href?: string;
  category: string;
  desc: string;
  image?: string;
  logo?: string;
}

export const portfolio: PortfolioItem[] = [
  {
    name: "Pittsburgh North Golf Club",
    url: "pittsburghnorthgc.com",
    category: "Golf Course",
    desc: "Full course website with tee time integration and membership portal.",
    image: "/sites/pittsburgh-north/hero.jpg",
  },
  {
    name: "Cirigliano Plumbing",
    url: "ciriglianoplumbingllc.com",
    href: "/sites/cirigliano-plumbing",
    category: "Plumbing",
    desc: "Family-owned South Hills plumber. 24/7 emergency service, trenchless sewer repair, and honest pricing.",
    image: "/sites/cirigliano/crew-work.jpg",
    logo: "/sites/cirigliano/logo.png",
  },
  {
    name: "Nicholas Electric Co.",
    url: "nicholaselectric.com",
    href: "/sites/nicholas-electric",
    category: "Electrical",
    desc: "Old-home electrical specialists since 1978. Knob & tube rewiring, EV chargers, and 24/7 emergency service.",
    image: "/sites/nicholas-electric/hero.jpg",
    logo: "/sites/nicholas-electric/logo.png",
  },
  {
    name: "Zeke & Son Roofing",
    url: "zekeandsonroofing.com",
    href: "/sites/zeke-son-roofing",
    category: "Roofing",
    desc: "Three generations since 1949. Shingle, flat, and slate roofing. Post-Gazette Fan Favorites 1st Place.",
    image: "/sites/zeke-son/slide1.jpg",
    logo: "/sites/zeke-son/logo.png",
  },
  {
    name: "Patriot Pest Control",
    url: "patriotpestcontrol.net",
    href: "/sites/patriot-pest-control",
    category: "Pest Control",
    desc: "Family-owned since 1995. Termites, bed bugs, rodents, and humane wildlife removal. BBB A+.",
    image: "/sites/patriot-pest/termites.jpg",
    logo: "/sites/patriot-pest/logo.png",
  },
  {
    name: "Grand View Golf Club",
    url: "pittsburghgolf.com",
    href: "/sites/grand-view-golf",
    category: "Golf Course",
    desc: "\"The Monster on the Mon.\" Public 18-hole course with skyline views and on-site Italian steakhouse.",
    image: "/sites/grand-view/hole14.jpg",
    logo: "/sites/grand-view/logo.png",
  },
  {
    name: "Caliguri's Academy of Martial Arts",
    url: "academyofmartialarts.org",
    href: "/sites/caliguris-martial-arts",
    category: "Martial Arts",
    desc: "Birthplace of MMA in America. Grand Master Frank Caliguri, 10th-degree black belt. Training champions since 1971.",
    image: "/sites/caliguris/stage.jpg",
  },
  {
    name: "Three Rivers Pickleball Club",
    url: "3riverspickleball.com",
    href: "/sites/three-rivers-pickleball",
    category: "Sports & Rec",
    desc: "12 indoor courts, pro shop, and craft beer lounge. Open play, leagues, and tournaments.",
    image: "/sites/three-rivers-pickleball/hero.jpg",
    logo: "/sites/three-rivers-pickleball/logo.jpg",
  },
  {
    name: "D'n A Custom Home Builders",
    url: "dnaconstructioninc.com",
    href: "/sites/dna-custom-homes",
    category: "Home Builder",
    desc: "BuildZoom top 15%. Fully custom homes, owner-builder program, and design-build under one roof.",
    image: "/sites/dna-homes/completed-home.png",
    logo: "/sites/dna-homes/logo.png",
  },
  {
    name: "John C.R. Kelly Realty",
    url: "jcrkelly.com",
    href: "/sites/kelly-realty",
    category: "Property Mgmt",
    desc: "Multi-generational property management since 1960. 50+ active listings, in-house maintenance.",
    image: "/sites/kelly-realty/hero.jpg",
  },
  {
    name: "Inspirational Designs",
    url: "inspirationaldesignspgh.com",
    href: "/sites/inspirational-designs",
    category: "Interior Design",
    desc: "Kitchen & bath design specialist. 84+ projects, VIP styling experience. BBB A+.",
    image: "/sites/inspirational/kitchen1.jpg",
    logo: "/sites/inspirational/logo.png",
  },
  {
    name: "My Family Memory",
    url: "myfamilymemory.com",
    category: "Web Application",
    desc: "Digital platform for preserving and sharing family stories and memories.",
    image: "/sites/myfamilymemory/hero.png",
  },
  {
    name: "WeatherMin",
    url: "weathermin.org",
    category: "Non-Profit",
    desc: "Weather monitoring organization with real-time data visualization.",
    image: "/sites/weathermin/hero.png",
    logo: "/sites/weathermin/icon.png",
  },
  {
    name: "Rental Helper",
    url: "rental-helper.com",
    category: "SaaS",
    desc: "Property management tool for landlords and tenants.",
    image: "/sites/rental-helper/hero.png",
    logo: "/sites/rental-helper/logo.png",
  },
  {
    name: "Vote for Charlie",
    url: "voteforcharlie.org",
    category: "Campaign",
    desc: "Political campaign website with donor engagement and event scheduling.",
    image: "/sites/voteforcharlie/portrait.jpg",
  },
  {
    name: "107 Certified",
    url: "107certified.me",
    category: "Professional",
    desc: "FAA drone certification resources and training portal.",
    image: "/sites/107certified/hero.png",
  },
  {
    name: "Edgewood Monuments",
    url: "edgewoodmonuments.com",
    href: "/sites/edgewood-monuments",
    category: "Memorial",
    desc: "Family-owned since 1975. Custom granite headstones, in-house engraving, and 5 showroom locations across the West Coast.",
    image: "/sites/edgewood-monuments/hero.png",
    logo: "/sites/edgewood-monuments/logo.svg",
  },
  {
    name: "Varney Family Law",
    url: "varneyfamilylaw.com",
    href: "/sites/varney-family-law",
    category: "Law Firm",
    desc: "Mesa AZ family law attorney. Divorce, custody, grandparent rights, and juvenile cases. 30+ years combined legal and social work experience.",
    image: "/sites/varney-family-law/hero.jpg",
    logo: "/sites/varney-family-law/logo.png",
  },
  {
    name: "FAB Quantum Harmony",
    url: "fabquantumharmony.com",
    href: "/sites/fab-quantum-harmony",
    category: "Wellness",
    desc: "Quantum healing and wellness practice in Phoenix. Virtual and in-home sessions with founder Frances Archuleta-Bess.",
    image: "/sites/fab-quantum-harmony/hero.jpg",
    logo: "/sites/fab-quantum-harmony/logo.jpeg",
  },
  {
    name: "School Systems Alliance",
    url: "ssak12.com",
    href: "/sites/ssa-k12",
    category: "Education",
    desc: "Executive coaching, search, and leadership development for K-12 education leaders. Superintendent and cabinet-level consulting.",
    image: "/sites/ssa-k12/hero-bg.jpg",
    logo: "/sites/ssa-k12/logo.jpg",
  },
  {
    name: "Big Door Realty",
    url: "bigdoorrealty.com",
    href: "/sites/big-door-realty",
    category: "Real Estate",
    desc: "Tempe AZ real estate brokerage. Home search, flat fee listings, buyer representation, and investment advisory.",
    image: "/sites/big-door-realty/hero.jpg",
    logo: "/sites/big-door-realty/logo.png",
  },
  {
    name: "Palace Auto Detail",
    url: "palaceautodetail.com",
    href: "/sites/palace-auto-detail",
    category: "Auto Detail",
    desc: "Premium auto detailing in Tempe. Ceramic coating, paint correction, and full interior detail. Luxury vehicles a specialty.",
    image: "/sites/palace-auto-detail/hero-amg.jpg",
    logo: "/sites/palace-auto-detail/logo.png",
  },
  {
    name: "Vitesse Worldwide",
    url: "vitesseworldwide.com",
    href: "/sites/vitesse-worldwide",
    category: "Logistics",
    desc: "Global transportation since 1987. Aircraft charter, ground transport, and executive protection across 111 countries.",
    image: "/sites/vitesse-worldwide/charter-quote.jpg",
    logo: "/sites/vitesse-worldwide/logo-white.png",
  },
  {
    name: "ServPro Phoenix",
    url: "servprophoenix.com",
    href: "/sites/servpro-phoenix",
    category: "Restoration",
    desc: "24/7 emergency restoration. Water damage, fire damage, mold remediation, and commercial services across the Phoenix metro.",
    image: "/sites/servpro-phoenix/team-action.jpg",
  },
  {
    name: "MBA Real Estate",
    url: "mba-re.com",
    href: "/sites/mba-real-estate",
    category: "Property Mgmt",
    desc: "Tempe AZ property management since 2009. BBB A+ rated. Residential and commercial management with 30+ years combined experience.",
    image: "/sites/mba-real-estate/hero.jpg",
  },
  {
    name: "CMP Holdings",
    url: "cmpholdings.net",
    href: "/sites/cmp-holdings",
    category: "Holdings",
    desc: "Diversified holding company with divisions in real estate, technology, infrastructure, and professional services.",
  },
  {
    name: "MRI Software",
    url: "mrisoftware.com",
    href: "/sites/mri-software",
    category: "Enterprise SaaS",
    desc: "Real estate software for innovators. 45,000+ clients across 170+ countries. Property management, accounting, and investment platforms.",
    logo: "/sites/mri-software/logo-icon.png",
  },
  {
    name: "Harbor Counseling",
    url: "theharborcounseling.com",
    href: "/sites/harbor-counseling",
    category: "Therapy",
    desc: "Trauma-focused therapy practice. 3 clinicians specializing in anxiety, depression, PTSD, and relationship issues. Telehealth available.",
    image: "/sites/harbor-counseling/hero.jpg",
    logo: "/sites/harbor-counseling/logo.jpg",
  },
  {
    name: "Anderson's Nutrition",
    url: "andersonsnutrition.com",
    href: "/sites/andersons-nutrition",
    category: "Health",
    desc: "Dietitian nutritionist with 6 locations across Arizona and Pennsylvania. Nutrition counseling, meal planning, and metabolic testing.",
    image: "/sites/andersons-nutrition/hero.png",
    logo: "/sites/andersons-nutrition/logo.png",
  },
  {
    name: "Western Cleaning Solutions",
    url: "westerncleaningsolutions.com",
    href: "/sites/western-cleaning-solutions",
    category: "Cleaning",
    desc: "Commercial cleaning in Tempe AZ. BBB A+ rated, Green Business Bureau certified. Office, carpet, and post-construction cleaning.",
    image: "/sites/western-cleaning-solutions/hero.jpg",
    logo: "/sites/western-cleaning-solutions/logo.png",
  },
  {
    name: "Koa Counseling & Consulting",
    url: "koacc.com",
    href: "/sites/koacc",
    category: "Therapy",
    desc: "Trauma-focused therapy in Tempe. Somatic Experiencing, EMDR, IFS, and ketamine-assisted therapy with 11+ years experience.",
    image: "/sites/koacc/hero.jpg",
    logo: "/sites/koacc/logo.png",
  },
  {
    name: "LCR Law Office",
    url: "lcrlawoffice.com",
    href: "/sites/lcr-law-office",
    category: "Law Firm",
    desc: "The Law Offices of La-Zondra C. Randolph. Orlando FL practice covering family law, criminal defense, personal injury, and business litigation.",
    image: "/sites/lcr-law-office/attorney.png",
    logo: "/sites/lcr-law-office/logo.png",
  },
  {
    name: "LeBaron Carroll",
    url: "lebaroncarroll.com",
    href: "/sites/lebaron-carroll",
    category: "Insurance",
    desc: "Rethink how you buy insurance. 20+ products across business, personal, and employee benefits. 3 offices in Arizona and Utah.",
    image: "/sites/lebaron-carroll/poster-image.png",
    logo: "/sites/lebaron-carroll/logo-white.png",
  },
  {
    name: "Great Bell Inc",
    url: "greatbellinc.com",
    href: "/sites/great-bell-inc",
    category: "IT Services",
    desc: "Enterprise IT consulting and staffing. Data migration, system integration, and PMaaS for Fortune 100 clients. Global delivery model.",
  },
  {
    name: "East Valley Mediator",
    url: "eastvalleymediator.com",
    href: "/sites/east-valley-mediator",
    category: "Mediation",
    desc: "PK Jordan — 30+ years negotiation experience. Divorce, business disputes, real estate, and education advocacy mediation in Gilbert AZ.",
    image: "/sites/east-valley-mediator/pk-jordan-headshot.jpg",
  },
  {
    name: "The Marshall Law Firm",
    url: "themarshalllawfirmpllc.com",
    href: "/sites/marshall-law-firm",
    category: "Law Firm",
    desc: "Houston TX law firm. Family law, criminal defense, personal injury, and business litigation. Founded by Desir\u00e9e Flye Marshall.",
    image: "/sites/marshall-law-firm/about.jpg",
    logo: "/sites/marshall-law-firm/logo.jpg",
  },
  {
    name: "The Peterson Law Firm",
    url: "thepetersonlawfirm.com",
    href: "/sites/peterson-law-firm",
    category: "Law Firm",
    desc: "Tempe AZ family law and bankruptcy. 144+ Google reviews, 4.7 stars. Divorce, custody, Chapter 7 and Chapter 13 filings.",
    image: "/sites/peterson-law-firm/hero-bg.jpg",
    logo: "/sites/peterson-law-firm/logo.png",
  },
  {
    name: "Arizona Law Group",
    url: "arizonalawgroup.com",
    href: "/sites/arizona-law-group",
    category: "Law Firm",
    desc: "Family law, criminal defense, and personal injury. 12 attorneys, 10 Phoenix metro offices, 400+ reviews at 4.8 stars.",
    image: "/sites/arizona-law-group/hero.jpg",
  },
  {
    name: "AZOffices",
    url: "azoffices.com",
    href: "/sites/az-offices",
    category: "Office Space",
    desc: "Executive office suites, virtual offices, and meeting rooms across Tempe, Gilbert, and Phoenix since 2002.",
    image: "/sites/az-offices/office-4.jpg",
  },
];
